### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by Smrtnyk** [pyatyispyatil/flame-chart-js#1]
The flame chart is amazing and probably the best out there
but I am currently struggling with performance where I have about 160k function calls to visualize

What I noticed there are extremely many calls to walk function and each takes about .5s
Also chart rerenders(repaints) all the time on click and mouse movies, zooms etc..
Maybe we could improve this somehow?
I could fork and commit a PR for improvements if you could give me an advice on what could be improved, which parts etc...

I can also provide a sample json file with data formatted and ready to be used in chart options

**Comment by pyatyispyatil** [comment]
Hey! It's very cool that you liked this project. I took inspiration from Chrome DevTools and ended up with this project.

Yes, there are some performance issues and I'm working on them in this Pull Request (https://github.com/pyatyispyatil/flame-chart-js/pull/2). If you have the opportunity to test it on your data, then it would be very good. And if there is an opportunity to give them to me, then I will also be grateful and try to test the flame chart on them.

Also the code was written in a hurry and I am currently trying to fix most of the most critical performance issues. At the moment there are still problems with the tooltip, but I will try to solve them as soon as possible.

**Comment by Smrtnyk** [comment]
[data.zip](https://github.com/pyatyispyatil/flame-chart-js/files/6207885/data.zip)
This is the zip with json file
it is about 19mb
and aproximately about 170k function calls
It is the real data, what I profiled using my custom built profiler

I will check the pull request tonight and let you know how it behaves

**Comment by Smrtnyk** [comment]
![Capture](https://user-images.githubusercontent.com/31451544/112546959-6d2c8600-8dba-11eb-9903-4d89ebc580ca.PNG)

I have loaded the json with the version from pull request
Performance seems much better, it really zooms much faster now but seems like there are issues with rendering
I attached the screenshot

Great work by the way, I see the project is pretty new but it is amazing
It replicates the chrome flame chart so well and visualization and detail level is incredible

**Comment by pyatyispyatil** [comment]
I completely forgot to mention that you had to specify a new `settings` argument in the constructor with the `performance` parameter set to `true`. This would enable even faster rendering. Anyway, I already made this the default in the last commit.

Your data is now rendered at the maximum zoom from 50 FPS on my MacBook Pro, which seems very cool. =)

As for the glitches in the screenshot, it's strange, I couldn't reproduce something like that. And what kind of browser is used? Yes, by the way, in your data, all nodes have a white color (#FFF).

**Comment by Smrtnyk** [comment]
Ah yeah the color I messed it up while generating the json file in node script
In my app I have a mapper to map the module name to corresponding color
Forgot to include it in the script

I am also not sure why It got rendered like that, maybe I messed something up
I will try it again after you merge this pull request to master

**Comment by Smrtnyk** [comment]
Also wanted to ask is there some plan for this library?
Like a roadmap or something?

Not sure if you plan to invest much time into this but I have some ideas for features etc..

**Comment by pyatyispyatil** [comment]
I don't have any special roadmap, but soon I want to supplement this project with the ability to write plugins for rendering various data (screenshots, network timelines, etc.), so as not to turn it into a kind of devtools-frontend and classes of 2-3k lines.

But if you have something to offer, then you can create an issue for it. =)

**Comment by Smrtnyk** [comment]
![Capture](https://user-images.githubusercontent.com/31451544/112634011-59286900-8e3a-11eb-9c1d-c09fd2d2fada.PNG)
I also just tried the updated example page and also have issues with rendering

**Comment by Smrtnyk** [comment]
![Capture](https://user-images.githubusercontent.com/31451544/112634190-90971580-8e3a-11eb-989f-aadbaa05c743.PNG)
This is from firefox

**Comment by pyatyispyatil** [comment]
Hmm, it looks like a problem with clearing the canvas. Can you checkout at this branch https://github.com/pyatyispyatil/flame-chart-js/pull/3 and check the reproduction?

**Comment by Smrtnyk** [comment]
I cloned the repo and tested the branch, still the same

**Comment by Smrtnyk** [comment]
I'll try to debug on my end to see which part could cause canvas not to clear
Code is pretty complex but maybe I will have luck

**Comment by Smrtnyk** [comment]
this.ctx = canvas.getContext('2d', { alpha: false });

This alpha property causes the issue
After removing it works fine for me

**Comment by Smrtnyk** [comment]
I googled a bit and seems like this alpha causes issues on chrome
{ alpha: true,
premultipliedAlpha: true,
  preserveDrawingBuffer: false }
  This setting also worked for me

**Comment by pyatyispyatil** [comment]
Very strange, because these `premultipliedAlpha`,` preserveDrawingBuffer` parameters only work for webgl context, according to [mdn](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext).

I would not like to make the canvas transparent, because this slows down the render.

Well, I still already redid the render and added support for firefox - there were just problems with the transparency of the canvas and with the fonts.

In theory, it should help. If possible, look at this thread again. I will be grateful. =)

**Comment by Smrtnyk** [comment]
I checked your PR with latest commit
Works on chrome 

But on firefox zoom incrementiation is very low, steps are too short

**Comment by pyatyispyatil** [comment]
It seems to me that you have some very magical computer on which you can catch any error, which is great.)

Well, I've tried fixing animation lags in firefox (https://github.com/pyatyispyatil/flame-chart-js/pull/3/commits/01d15bd7313d0dbe707d9de497d23777cb290b06), but not sure if it helps. The profiling options in firefox are extremely limited and it is not at all clear what exactly happened in your case that the scaling slowed down. In theory, I rely on the standard `mousewheel` events to return an identical result each time it is fired.

In my firefox, the flame chart is much slower than chrome, but scaling is basically the same speed.

**Comment by Smrtnyk** [comment]
I am using companys DELL that runs windows so maybe we have differences in how our graphic cards work or something

I rebased on latest commit and firefox still increments weirdly
Not an issue for me since I am using the app with flame chart only on chrome, but I guess for other users could be an issue

On chrome it looks great and is blazing fast with my big data jsons that I record with profiler

**Comment by pyatyispyatil** [comment]
I published the [version](https://github.com/pyatyispyatil/flame-chart-js/releases/tag/v1.1.3) with the latest edits, so you can install it from npm and keep using it.)

**Comment by Smrtnyk** [comment]
Tnx man, you are such a great guy :D

I will close this issue now since it works for me how it should
