### ISSUE TITLE
Can we have a roadmap to get more people involved?

### ISSUE THREAD

**Issue by TsangKalung** [pyatyispyatil/flame-chart-js#14]
## My Point of View

Wow! What a amazing project! Thank you so much to release this project to help us with performance optimization analysis needs. I will briefly explain what I think is the advantage of this project.Recently I am developing a tool to analyze online performance data. I have two options:

- [Chrome DevTools](https://developer.chrome.com/docs/devtools/): Powerful and comprehensive performance analysis tool, but it is too complicated, it is inconvenient to carry out secondary development and release a separate npm package, and it also requires the use of [gn](https://gn.googlesource.com/gn/) tools that are difficult to use.
- [Trace Viewer](http://google.github.io/trace-viewer/): Old school performance tool that is also perfectly compatible with the [trace format](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview) and is very lightweight, but its problem is that the code style is difficult to maintain.

So both options had their problems until I discovered this project, which provides clean code logic and a convenient plugin mechanism. Thanks again! Its an incredible project!

## Why It Would Be Better To Have a Roadmap

Although this project is lightweight and easy to expand, it is believed that the arrival of a roadmap **will make this project a very popular project!** (so many programmers have the need to develop custom performance analysis tools)

Let me mention a few possible roadmaps and why this is needed：

- **TypeScript:** Bring in TS can make codebase easier to maintain, this codebase has been already complicated,using TS can bring stronger vitality to the project and facilitate more people to participate in the development.
- **Compatible with Trace Event Format:** [Trace Event Format](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview) is the most popular profile format using in web developers,especially the flow event is incredible.Compatible with this format can make this project more powerful.

Finally,I have full enthusiasm to participate in the development of this project!

**Comment by Smrtnyk** [comment]
I think having a roadmap is a great thing.
I already created a PR #10 for ts last year but project changed so much that it became completely obsolete.
Nikolay create a great software here and I agree that there is a potential to be extremely popular, given the fact that at company where I work we easily visualize over 1 milion of function calls.

**Comment by pyatyispyatil** [comment]
Hi guys. Thank you very much for the kind words.)
Unfortunately, last year I did not find free time to support this project and changed the company where I work. This means that I have less free time and this project is no longer related to my main job.(
But you can work together and try to move along the roadmap you describe in this issue. For my part, I can provide support with code reviews and tips.)

About the proposed roadmap:
1. The TypeScript migration is partly done by @Smrtnyk and you can take the manual into your own hands.)
2. Compatible with trace event format was also in my plans, I already did it in [another project] (https://github.com/overlookerjs/overlooker/blob/master/src/stats/index.js #L164 ), and we can take the implementation from this project. I'm pretty sure this trace event handler works with Chrome timeline records, but not sure about others (Android, Linux trace events, etc).

**Comment by Smrtnyk** [comment]
I plan to return back to the typescript PR next week if anyone else doesn't want to work on it.
But will start from scratch because the current PR is based on the old architecture which is obsolete now with plugins system.

**Comment by danatcofo** [comment]
I am using this in my company's application called Prefix where we visualize traces of server side requests.  Its pretty awesome and did also contribute some stuff as well.  In fact going to fix a visualization bug here soon where we have overlapping text on spans that overlap due to them representing async function calls.  Would love to see a roadmap.

**Comment by pyatyispyatil** [comment]
I tried to describe all my wishes in the context of this project and got such a roadmap. Enough for about a year of development.)
https://github.com/pyatyispyatil/flame-chart-js/wiki/Roadmap

**Comment by Smrtnyk** [comment]
Since @pyatyispyatil already created a roadmap and it can be found in here https://github.com/pyatyispyatil/flame-chart-js/wiki/Roadmap I will close this issue then
