### ISSUE TITLE
Introduce basic unit tests

### ISSUE THREAD

**Issue by Smrtnyk** [pyatyispyatil/flame-chart-js#20]
We should add some basic unit tests for data transformation, like nodes clustering etc...
Lots of these functions are testable.
Maybe jest would be an option?

**Comment by Smrtnyk** [comment]
@pyatyispyatil  do you have some thought on this?
I would like to add some tests.
Unit tests, maybe even e2e tests.
Would like to work on it if you have some ideas.
I have never really tested canvas, but we can also test individual classes.
Project is very complex and is easy to create regressions.

**Comment by pyatyispyatil** [comment]
I think you are right, only clustering and functions close to it are testable. Other places are too hard to cover with e2e and other tests - first we need a mocks for the rendering engine and interaction engine, and then we can write some tests.

It would be a good idea for you to try writing tests for clustering. Later it will be easy to implement span intervals in the flame chart.)

A little later I will describe in more detail in the issue about intervals.

**Comment by Smrtnyk** [comment]
Are you fine with jest, or you prefer some other testing framework?
I am using swc/jest at company and it is very nice and fast transformer.

**Comment by pyatyispyatil** [comment]
Jest is good for me, you can include this in the project.)

**Comment by pyatyispyatil** [comment]
And yes, we can also try swc. I don't know that many facts about this compiler, but I do know that it's very fast.)

**Comment by Smrtnyk** [comment]
Cool, I will add some of them today
and then we can start building on that
