### ISSUE TITLE
Npm install fails because of rollup-plugin-uglify

### ISSUE THREAD

**Issue by Smrtnyk** [pyatyispyatil/flame-chart-js#33]
Seems like rollup-plugin-uglify has a peer dep of rollup < 2 so npm install fails.
Also that plugin hasn't received an update for a long time.
Maybe we could move from rollup to esbuild?

**Comment by pyatyispyatil** [comment]
I fully agree to this.)
And yes we can move to esbuild.

**Comment by Smrtnyk** [comment]
I will create a new issue to switch to esbuild, or even to vite since we only need build system for examples dir
