### ISSUE TITLE
Using the library in the browser

### ISSUE THREAD

**Issue by datduyng** [pyatyispyatil/flame-chart-js#38]
Great tool. can you please produce a dist file to be able to use it directly from browser with vanilla JavaScript?

**Comment by pyatyispyatil** [comment]
It seems to be able to do what needs to be done. In the latest version of the library, I changed the dist (https://github.com/pyatyispyatil/flame-chart-js/commit/62d9a8a77395503ed798cdef86d7ef62f99640f2). Can you please try to use it and give feedback?
