### ISSUE TITLE
 if timeframe-selector support cpu usage show?

### ISSUE THREAD

**Issue by hjmhjms** [pyatyispyatil/flame-chart-js#39]
it's perfect if timeframe-selector support cpu usage show .  Do you have a plan to show cpu usage just many points.

**Comment by jburrow** [comment]
cpu and memory usage would be useful to have rendered in a timeframe or similar view; I have started experimenting locally with this myself. If I get it working I will PR it

**Comment by pyatyispyatil** [comment]
@hjmhjms I added support for charts for the timeframe-selector and separately moved the ability to display charts to a separate plugin (in v2.3.0). Please give it a try and I'd love any feedback, especially on how easy it is to use the new feature. If you encounter any difficulties, you can report in this issue.)
