### ISSUE TITLE
[Feature request] Timeframe selector similar to chrome profiler

### ISSUE THREAD

**Issue by Smrtnyk** [pyatyispyatil/flame-chart-js#4]
You already said in the issue I created about performance that you do not have specific roadmap and feature list but that you plan to maybe implement the timeframe selector

I created this ticket to have tracking of it. 
Not sure how much time you plan to invest in this project and if this will not happen in the near future feel free to close this :D
I really enjoy this project and so far there is no better flame chart out there

I would contribute the feature but I am not the best with canvas API, I mostly messed with svgs and d3.js

**Comment by pyatyispyatil** [comment]
Well, I really have plans to implement a timeframe selector.

Until recently, there were still performance problems and it was not possible to add any other functionality to the render queue - for sure, frames larger than 16ms would appear.

In the latest version (1.3.1), I managed to reduce the render time to 4ms with 1kk nodes, and this already looks encouraging.

As I mentioned earlier, I need to develop a plugin system so as not to turn the flame chart class into one huge sheet of code.

Initially, I needed this project for work purposes. But further development is already going more in the context of a hobby. So, most likely I will be able to do its development more on weekends and not so often. But I'm pretty sure I won't throw it.)

**Comment by pyatyispyatil** [comment]
And I do not understand at all why the flame chart in chrome devils is so terribly slow, seriously.))

They spend too much on detailed rendering when it can be simplified and the UX improved.

**Comment by Smrtnyk** [comment]
Yeah it has some issues
Also your flame chart is more UX friendly because it looks more intuitive on zoom, I don't get stretched nodes on click
I recently recorded a file with 2.7 milion of function calls and chart is still pretty usable, it lags a bit when zoom out is maxed but if I zoom in it gets fluid
Awesome work

When it comes to timeframe selector I agree the plugin aproach would be good
Chart already grew a bit in lines

I also noticed some unused functions like debounce and some parameters

Have you thought turning the codebase to typescript and add some linting? I could help you with that

**Comment by pyatyispyatil** [comment]
Yes, I would like to translate the codebase into typescript and add a linter. And I would be very happy if you can help with that.)

As for the linter, I would like to keep the code style as close as possible to what I'm using, if possible.

**Comment by Smrtnyk** [comment]
I did some work on typescript
Will push into a branch when I am finished

When it comes to build process I will do the ts part and not sure about rollup stuff, I guess you could help to bundle it and minify after ts does its job

**Comment by pyatyispyatil** [comment]
It seems like I'm done with plugin development. You can try to clone the branch from this pull request (https://github.com/pyatyispyatil/flame-chart-js/pull/8) and see how it works. In principle, I tested most of the use cases, but I may have missed something.

I would be very grateful if you could help me test the timeframe selector better and give a resolution to see if everything is okay. 
And after that I will publish a new version of the package.)

**Comment by Smrtnyk** [comment]
Sure, I was busy on the weekend but will try it today after work
I recently recorded a trace with about 1 milion function calls on a customer website, will test the new flame chart with selector on that

**Comment by Smrtnyk** [comment]
Alright, the timeframe selector plugin works amazing and looks amazing
Couldn't find any issue with it

Impressive work :D 

I would have one question regarding the plugin interface usage

I have a use case where I have a chart on the right and function list on the left which has agregated data and then when I click the function in the list it selects all the functions with the same name in the cart and expands the list to show function instances
Then when I click the function instance in the list then it highlights the same one in the chart

Will I be able to make that behavior with new plugin interface?

**Comment by pyatyispyatil** [comment]
Oh, cool. Glad you liked it.)

At the expense of zoom to a specific function: in the same pull request, I added a couple of public methods for navigating the flame chart. The setZoom method accepts two numbers, and you can pass in the start and config values ​​of the execution time of your function. In theory, it will work.) You can read about this in README.md.

Now I myself am thinking about highlighting the necessary nodes in the flame chart. I want to be able to quickly highlight all executions of functions from a specific file. I think that in the next two weeks I will come up with something on this score. So far, it is seen as an external mutation of the data with which the flame chart was initialized, and a rerender of the flame chart. Currently, while the data is being converted to an internal format and links do not work, so changes to the original data do not affect the rendering in any way. (

**Comment by Smrtnyk** [comment]
I alredy did some work but stuff changed a bit with new plugin system
On thursday is a public holiday here in Austria so I will have time to rebase and add more typings and open a PR so we can then together finalize it
