### ISSUE TITLE
introduction of opinionated autoformating? (prettier)

### ISSUE THREAD

**Issue by jburrow** [pyatyispyatil/flame-chart-js#41]
Hi, Would you accept a PR introduced prettier to auto-format the all the code? This would reduce PR review cost? So including all the .js, configs and examples?

**Comment by pyatyispyatil** [comment]
I just added the pre-commit hook myself, thanks for the tip.) https://github.com/pyatyispyatil/flame-chart-js/commit/37497887392fad95d6faadcb866f1e4579c8e489 https://github.com/pyatyispyatil/flame-chart-js/commit/9087d924e0c560a5047dc97b55cdcdbbd87e41a6
