### ISSUE TITLE
README.md example fails

### ISSUE THREAD

**Issue by abitrolly** [pyatyispyatil/flame-chart-js#43]
I am trying to run the code from the readme at https://playcode.io/

First problem is that the playground is unable to find the latest version of the library.

![image](https://user-images.githubusercontent.com/8781107/209342525-d6a2d997-b0ec-41db-b41f-0c2393a7f8c5.png)

And then the example fails with this error.
```
TypeError: data is undefined
setData@https://preview-new.playcode.io/ line 18 > injectedScript:1960:7
WaterfallPlugin@https://preview-new.playcode.io/ line 18 > injectedScript:1907:12
FlameChart@https://preview-new.playcode.io/ line 18 > injectedScript:2240:27
@https://preview-new.playcode.io/ line 18 > injectedScript:85:18
dn@https://preview-new.playcode.io/ line 6 > injectedScript:18:5449
```

**Comment by abitrolly** [comment]
I had to remove a couple if lines to make it work. The last one was this,

```
    waterfall: { /* ... */ },
```

**Comment by pyatyispyatil** [comment]
The readme contains only an exemplary usage code with comments that allows you to understand how to use the library. For a fully working version, you should look into the example folder.)

**Comment by abitrolly** [comment]
@pyatyispyatil any ideas why latest version is not importable by JS playgrounds?

**Comment by pyatyispyatil** [comment]
Most likely something is wrong with the playground, since all versions are available in npm.(

**Comment by abitrolly** [comment]
It is not the only one. Perhaps something had changed about packaging format, but I am not sure how to check if module discovery with NPM works correctly.
