### ISSUE TITLE
Custom span rendering？

### ISSUE THREAD

**Issue by dingjunweibjkanyun** [pyatyispyatil/flame-chart-js#53]
Is it not supported?
like this
![image](https://github.com/pyatyispyatil/flame-chart-js/assets/135958780/93e8e6f1-1f99-4b10-864a-81d5b6fa71f6)

If not supported? Can you provide a way to modify the source code?

**Comment by pyatyispyatil** [comment]
In v3.1.0 you can use badge prop in each node.
