### ISSUE TITLE
TypeError: flameChart.setData is not a function

### ISSUE THREAD

**Issue by MrThanlon** [pyatyispyatil/flame-chart-js#54]
The example of README doesn't worked, 
```
import FlameChart from 'flame-chart-js'
```
throw no default error, so
```
import { FlameChart } from 'flame-chart-js'
```
Then flameChart = new FlameChart({...}), and it works, but flameChart.setData is undefined

**Comment by pyatyispyatil** [comment]
Oops, sorry, the readme is a little outdated.  You can use the `setNodes` method to set some data like this in the example: https://github.com/pyatyispyatil/flame-chart-js/blob/096773686ca188b634c19cc481dd31019a3c8333/example/src/components/charts/flame-chart-wrapper.tsx#L96

I will update readme soon.)

**Comment by MrThanlon** [comment]
How to update the data of FlameChartContainer? Or just remove/destroy and renew?

**Comment by pyatyispyatil** [comment]
> It seems that we can use `FlameChartPlugin.setData` to update the data. So, how can we remove `FlameChartPlugin` from `FlameChartContainer`?

Method `setData` from `FlameChartPlugin` works the same as method setNodes from FlameChart class (method `setNodes` is a wrapper over method setData from `FlameChartPlugin`). Are you sure you need to remove this plugin?)

In general, if you need some kind of customized view, then you should use the container without everything and fill it with plugins yourself, as is done in the `FlameChart` class.

**Comment by MrThanlon** [comment]
I'm certain that I need to remove some plugins, such as the `FlameChartPlugin`, for multi-threaded programs where each thread is allocated one. The number of threads may change when updating the profile results, so it becomes necessary to add or remove certain `FlameChartPlugins`.

**Comment by pyatyispyatil** [comment]
Oh, okay. You can do the same as in this examples:
https://github.com/pyatyispyatil/flame-chart-js/blob/master/example/src/components/charts/custom-flame-chart.tsx
https://github.com/pyatyispyatil/flame-chart-js/blob/master/example/src/components/charts/flame-chart-container-wrapper.tsx
