### ISSUE TITLE
[Feature request] add Options for styling

### ISSUE THREAD

**Issue by marmoure** [pyatyispyatil/flame-chart-js#6]
it would be nice if we can add more styles 
i sent a pull request but that was only for my needs 
is there something else we can Add

**Comment by Smrtnyk** [comment]
I am working on typescript port, did like 80% of work but lately I am overloaded on my work so no time to finish it
Hopefully I do it in next weeks

I like the idea of styling, lets see what Nikolay says when he sees this

**Comment by pyatyispyatil** [comment]
Guys, I beg your pardon, but I started rewriting the whole project 2 days ago to implement the plugin system.(

All of this happens in this pull request https://github.com/pyatyispyatil/flame-chart-js/pull/7 and most of it has been completed. In the next couple of days I will be cleaning up the code and working on the plugin interface for more convenience.

This topic has already been discussed in other issue and then finally got 10 free days, some of which I want to devote to the revision of this project.

Along with the rework, I also plan to implement a time frame selector plugin and a network timeline plugin (something similar to a network waterfall in the performance tab).

After that, I can help with updating your edits for the new architecture.)

**Comment by pyatyispyatil** [comment]
In terms of style, I love this idea and I think it can be developed further.)

**Comment by marmoure** [comment]
okay this looks amazing
looking forward for the plugin system
and typescript support

**Comment by Smrtnyk** [comment]
Another Idea i have is to maybe add possibility to show function in passive timespan mode, like chrome does it with striped style
If function has a promise awaiting inside of it some of the time is spent on the awaiting it etc...

**Comment by pyatyispyatil** [comment]
@Smrtnyk I didn't quite understand what you mean.
Can you show a specific case in the screenshot?

**Comment by Smrtnyk** [comment]
![image (5)](https://user-images.githubusercontent.com/31451544/116893013-c3e67480-ac30-11eb-9bbf-eeaa5c337ffe.png)
Here is the screenshot from chrome profiler

**Comment by pyatyispyatil** [comment]
Oh, I get it. Yes, it will have to be done.

**Comment by pyatyispyatil** [comment]
Well, I finished refactoring and added a plugin system. Today I managed to add options for styling everything that is possible in the project (https://github.com/pyatyispyatil/flame-chart-js/commit/6dff7c3db4e308408f465d57bc89f06dc741d670). I have already published version 1.4.0 and there you can try the innovation.)

In the [example](https://pyatyispyatil.github.io/flame-chart-js/example/dist/index.html), I also added an interface for testing styles.

I will describe how to use plugins a little later in the readme, when I make a couple more plugins.

As for the rest of the features, I'm still working on it.

**Comment by marmoure** [comment]
it looks amazing i m gonna close that PR 
thanks you so much

**Comment by pyatyispyatil** [comment]
It's my pleasure.)
