### ISSUE TITLE
Bug: Plugin on select doesn't work for index zero on waterfall plugin and possibly other plugins that have handle select

### ISSUE THREAD

**Issue by wizardlyhel** [pyatyispyatil/flame-chart-js#61]
When handling selected region in a plugin, if `region.data === 0`, `null` is returned. However, `this.initialData[0]` is a valid region and should return data instead of `null`

https://github.com/pyatyispyatil/flame-chart-js/blob/fe2fe15df8e4ce542e984ed02fd5876d7298daa7/src/plugins/waterfall-plugin.ts#L87-L89

**Comment by pyatyispyatil** [comment]
Thank you very much for your bug report! =)

Fixed in [3.2.0](https://github.com/pyatyispyatil/flame-chart-js/releases/tag/v3.2.0)
