### ISSUE TITLE
FlameChart render go wrong when the container div width and heigh become 0

### ISSUE THREAD

**Issue by xyzt1402** [pyatyispyatil/flame-chart-js#62]
Hello, it's me again. I somehow use your chart in a modal ( antd component but i think other modal still fail). And if you close modal and reopen it, the chart can not be rendered and error happen that Canvas Context Element can't render on div which width and heigh are 0.

**Comment by pyatyispyatil** [comment]
Hello. These are limitations of the canvas itself, so you need to use an additional wrapper that has a minimum size greater than zero.
