### ISSUE TITLE
Default Time Range selection 

### ISSUE THREAD

**Issue by xyzt1402** [pyatyispyatil/flame-chart-js#65]
Is there any way to set default time range of the chart. for example: 
This 
![image](https://github.com/pyatyispyatil/flame-chart-js/assets/75368538/93e2da69-5c96-4efd-9224-964bf70d08ba)
Instead of this: 
![image](https://github.com/pyatyispyatil/flame-chart-js/assets/75368538/0bd0aa8f-3723-4747-a0bf-395cffa88c8f)
Or better, set a default time range with the start and end of a specific Node?

**Comment by pyatyispyatil** [comment]
You can achieve this behavior by using the `setZoom` method when initializing the flame chart:
```ts
const nodes = [
  { name: 'foo', start: 400, duration: 500 }
];

const flameChart = new FlameChart({
  data: nodes
});

flameChart.setZoom(nodes[0].start, nodes[0].start + nodes[0].duration);
```
