### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by brsanthu** [pyatyispyatil/flame-chart-js#71]
Any idea how to support dark theme? I could set colors for individual segments fine per dark theme but couldn't change the canvas background color which seems to be default to white.

**Comment by brsanthu** [comment]
I could set the background color as following and working great.

```
styles: {
        main: {
          backgroundColor: 'black',
        },
      }
```

**Comment by SagarChandra07** [comment]
install this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)
