### ISSUE TITLE
Move chart to typescript

### ISSUE THREAD

**Issue by Smrtnyk** [pyatyispyatil/flame-chart-js#9]
I will create this issue so we can have discussion about it here and to link pull request when I open one today or tomorrow

**Comment by pyatyispyatil** [comment]
Wow, that's cool. First time someone helps me so much on github.)

Yes, my code is probably complicated in places, there are still a lot of non-obvious interactions there. But it's still better than it was, I think.)

I will definitely review the code and send my edits to the mentioned Pull Request. In addition, today I have finalized a couple of plugins and the code has changed, conflicts have appeared. I'll take over the work to resolve them, so everything will be ok.)

I will try to do this on the weekend and finalize the typing - I’ll just add the necessary plugins for the rollup and set up transpilation to the js with header ts files for use in projects with pure javascript.

**Comment by Smrtnyk** [comment]
Your code is complex but it is amazing
I am very impressed by your coding skills and the result you produce. I can definitely see that you have a lot of experience in this.

I am not on that level for sure since I am only 2 years into this but I will try to contribute where I can because It is in my interest also. I am using the chart as an internal tool to debug my product on customers webpage.
I have built a tracer which records traces and then I have a viewer where I load the files and use this chart to inspect them.

I am glad if I can help you. After we finalize typescript next step would be to add linting which I can do for you and maybe add a github action that runs a build to make sure ts compiles and eslint has no errors.

**Comment by Smrtnyk** [comment]
Btw it seems we have similar jobs
I work as javascript agent developer at https://www.dynatrace.com/
And I see you are contributing to overlooker which seems like it is also doing with application performance monitoring? :D

**Comment by pyatyispyatil** [comment]
Thank you, I'm very flattered.)

In fact, I don't have much experience with canvas. As far as I remember, I only wrote Tetris on canvas quite a long time ago, about 4 years ago. It is also on my github.)

For the past two weeks I have been unforeseenly busy at my main job, unfortunately. (
I have set myself quite serious plans for the quarter and now I am trying to somehow implement what I have planned. Perhaps you saw from the abundance of patches that work is in progress, heh.)
As I solve most of the problems with work, I will return to the typescript. Most likely, I will even take the task into one of the sprints at the main work on revision and implementation. I hope this will be a priority for me before the implementation of new features in the flame chart.

Yes, apparently there is something similar in our works.)
I work in Avito. This is the second classified in the world (after craigslist.org) and you may be using olx, which is in the same holding with Avito. And I work in a team that deals with the performance of this project.

Overlooker is also my project, which was born at work. This can be said to be a framework for organizing frontend performance tests, a kind of core. Inside the company, on the basis of this core, I built frontend performance tests in CI/CD, and an interface with traces, screenshots, and metrics was built around this. Most of all it looks like lighthouse-ci, only I collect a lot more information about code execution and page loading.

I still want to also open-source this interface and the entire server side, but there is still too much internal code that should not be published. But someday it will hopefully happen.)

[And this is how it looks like.](https://user-images.githubusercontent.com/4976306/119259050-0d453680-bbd5-11eb-8936-46d5906606f2.png)

**Comment by Smrtnyk** [comment]
Wow, looks amazing. I am impressed by the solution
It must have saved you many bugs being reported in the work

I will also post our usecase of flame chart
![flame-chart-usecase](https://user-images.githubusercontent.com/31451544/119962338-3b48c300-bfa7-11eb-94cd-82a33ea20b42.png)

So on the left side there are lists of agregated data for each function
We can hover over the function in the list and it will highlight all the nodes in the chart with same key
Then if we click on the function in the list it opens all the function instances and then highlight the instance in the flame chart

I ported flame-chart to our repo and moved it to ts, it is still using the old version of the flame-chart with no plugin system and I tweaked the chart to work with the list bidirectional

My plan is after you finalize the ts work to try to get rid of our port and install your package from npm, and then extend it with plugin system to also work with the list if possible
